name: Deploy Website
on:
  push:
    branches: [ main ]

permissions:
  id-token: write # Required for requesting the JWT from GitHub
  contents: read  # Required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::329068432608:role/github-actions-invalidate-cloudfront-upload-s3 # Replace with your Role ARN
          aws-region: us-east-1 # Replace with your region

      - name: Sync S3
        run: aws s3 sync . s3://abhigyanchandrarastogi-portfolio --delete

      - name: CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id E344VXPUM5BXKM --paths "/*"
